# division por cero
try:
    10/0
except Exception as err:
    print(f'Error: {err}')
